
services:
  frontend:
    environment:
      - VITE_BACKEND_URL=http://localhost:80/api/
    build:
      context: ./frontend 
    depends_on:
      - backend
      - nginx
    volumes:
      - frontend-files:/app/dist

  nginx:
    build:
      context: ./nginx  
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - frontend-files:/usr/share/nginx/html/frontend
      - ./logs:/var/log/app
    logging:
      driver: "json-file"
      options:
        labels: "nginx"
        max-size: "1m"
        max-file: "10"

  backend:
    # environment:
    #   - FRONTEND_ORIGIN=http://localhost
    build:
      context: ./backend 
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - loki
    # volumes:
    #   - ./logs:/var/log/app
    logging:
      driver: "json-file"
      options:
        labels: "backend"
        max-size: "1k"
        max-file: "10"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      grafana-network:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    networks:
      grafana-network:
      
  loki:
    build:
      context: ./loki 
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/local-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      grafana-network:


  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      grafana-network:

  # alloy:
  #   image: grafana/alloy
  #   volumes:
  #     - ./alloy/config.alloy:/etc/alloy/config.alloy

networks:
  app-network:
    name: app-network
  grafana-network:
    name: grafana-network

volumes:
  frontend-files: