
services:
  frontend:
    environment:
      - VITE_BACKEND_URL=http://localhost:80/api/
    build:
      context: ./frontend 
    depends_on:
      - backend
      - nginx
    volumes:
      - frontend-files:/app/dist

  nginx:
    build:
      context: ./nginx  
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - frontend-files:/usr/share/nginx/html/frontend
      - ./logs:/var/log/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    # environment:
    #   - FRONTEND_ORIGIN=http://localhost
    build:
      context: ./backend 
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./logs:/var/log/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      app-network:
        # ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3001:3001
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    networks:
      app-network:
        # ipv4_address: 172.16.238.12
      
  loki:
    build:
      context: ./loki 
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/local-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml


  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

networks:
  app-network:
    name: app-network

volumes:
  frontend-files: