name: Run Tests on Push to Main

on:
  push:
    branches:
      - main

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        working-directory: ./backend
        run: pip install uv

      - name: Install dependencies
        working-directory: ./backend
        run: uv sync

      - name: Test ruff for lint
        working-directory: ./backend
        run: uv run ruff check .

      - name: Test pyright for type
        working-directory: ./backend
        run: uv run pyright

      - name: Run pytest for backend
        working-directory: ./backend
        run: uv run pytest

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run lint for frontend
        working-directory: ./frontend
        run: npm run lint
        
      - name: Run TypeScript check
        run: npx tsc --noEmit
        
      - name: Run test for frontend
        working-directory: ./frontend
        run: npm run test
